# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_tournoi
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Port (optional)
server.port=8080